picboard:
    resource: "@PicboardBundle/Controller/"
    type:     annotation
    prefix:   /

index:
    resource: "@IndexBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
