<?php

namespace PicboardBundle\Repository;

/**
 * PicUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
