<?php

namespace PicboardBundle\Repository;

/**
 * ThePictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThePictureRepository extends \Doctrine\ORM\EntityRepository
{
}
