<?php

namespace IndexBundle\Repository;

/**
 * SubCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCatRepository extends \Doctrine\ORM\EntityRepository
{
}
